import chisel3._

class RoundAndBuffer() extends Module {
  val io = IO(new Bundle {
    val counter         = Input(Bool())
    val stateReg_enable = Input(Bool())
    val round_in_0_0 = Input(UInt(64.W))
    val round_in_1_0 = Input(UInt(64.W))
    val round_in_2_0 = Input(UInt(64.W))
    val round_in_3_0 = Input(UInt(64.W))
    val round_in_4_0 = Input(UInt(64.W))
    val round_in_0_1 = Input(UInt(64.W))
    val round_in_1_1 = Input(UInt(64.W))
    val round_in_2_1 = Input(UInt(64.W))
    val round_in_3_1 = Input(UInt(64.W))
    val round_in_4_1 = Input(UInt(64.W))
    val round_in_0_2 = Input(UInt(64.W))
    val round_in_1_2 = Input(UInt(64.W))
    val round_in_2_2 = Input(UInt(64.W))
    val round_in_3_2 = Input(UInt(64.W))
    val round_in_4_2 = Input(UInt(64.W))
    val round_in_0_3 = Input(UInt(64.W))
    val round_in_1_3 = Input(UInt(64.W))
    val round_in_2_3 = Input(UInt(64.W))
    val round_in_3_3 = Input(UInt(64.W))
    val round_in_4_3 = Input(UInt(64.W))
    val round_in_0_4 = Input(UInt(64.W))
    val round_in_1_4 = Input(UInt(64.W))
    val round_in_2_4 = Input(UInt(64.W))
    val round_in_3_4 = Input(UInt(64.W))
    val round_in_4_4 = Input(UInt(64.W))

    val round_out_0_0 = Output(UInt(64.W))
    val round_out_1_0 = Output(UInt(64.W))
    val round_out_2_0 = Output(UInt(64.W))
    val round_out_3_0 = Output(UInt(64.W))
    val round_out_4_0 = Output(UInt(64.W))
    val round_out_0_1 = Output(UInt(64.W))
    val round_out_1_1 = Output(UInt(64.W))
    val round_out_2_1 = Output(UInt(64.W))
    val round_out_3_1 = Output(UInt(64.W))
    val round_out_4_1 = Output(UInt(64.W))
    val round_out_0_2 = Output(UInt(64.W))
    val round_out_1_2 = Output(UInt(64.W))
    val round_out_2_2 = Output(UInt(64.W))
    val round_out_3_2 = Output(UInt(64.W))
    val round_out_4_2 = Output(UInt(64.W))
    val round_out_0_3 = Output(UInt(64.W))
    val round_out_1_3 = Output(UInt(64.W))
    val round_out_2_3 = Output(UInt(64.W))
    val round_out_3_3 = Output(UInt(64.W))
    val round_out_4_3 = Output(UInt(64.W))
    val round_out_0_4 = Output(UInt(64.W))
    val round_out_1_4 = Output(UInt(64.W))
    val round_out_2_4 = Output(UInt(64.W))
    val round_out_3_4 = Output(UInt(64.W))
    val round_out_4_4 = Output(UInt(64.W))

  })

  val round           = Module(new Round())
  val stateRegister   = Module(new StateRegister())

  round.io.counter := io.counter
  stateRegister.io.enable := io.stateReg_enable
  round.io.round_in_0_0 :=  stateRegister.io.state_out_0_0
  round.io.round_in_1_0 :=  stateRegister.io.state_out_1_0
  round.io.round_in_2_0 :=  stateRegister.io.state_out_2_0
  round.io.round_in_3_0 :=  stateRegister.io.state_out_3_0
  round.io.round_in_4_0 :=  stateRegister.io.state_out_4_0
  round.io.round_in_0_1 :=  stateRegister.io.state_out_0_1
  round.io.round_in_1_1 :=  stateRegister.io.state_out_1_1
  round.io.round_in_2_1 :=  stateRegister.io.state_out_2_1
  round.io.round_in_3_1 :=  stateRegister.io.state_out_3_1
  round.io.round_in_4_1 :=  stateRegister.io.state_out_4_1
  round.io.round_in_0_2 :=  stateRegister.io.state_out_0_2
  round.io.round_in_1_2 :=  stateRegister.io.state_out_1_2
  round.io.round_in_2_2 :=  stateRegister.io.state_out_2_2
  round.io.round_in_3_2 :=  stateRegister.io.state_out_3_2
  round.io.round_in_4_2 :=  stateRegister.io.state_out_4_2
  round.io.round_in_0_3 :=  stateRegister.io.state_out_0_3
  round.io.round_in_1_3 :=  stateRegister.io.state_out_1_3
  round.io.round_in_2_3 :=  stateRegister.io.state_out_2_3
  round.io.round_in_3_3 :=  stateRegister.io.state_out_3_3
  round.io.round_in_4_3 :=  stateRegister.io.state_out_4_3
  round.io.round_in_0_4 :=  stateRegister.io.state_out_0_4
  round.io.round_in_1_4 :=  stateRegister.io.state_out_1_4
  round.io.round_in_2_4 :=  stateRegister.io.state_out_2_4
  round.io.round_in_3_4 :=  stateRegister.io.state_out_3_4
  round.io.round_in_4_4 :=  stateRegister.io.state_out_4_4

  stateRegister.io.state_in_0_0 := round.io.round_out_0_0
  stateRegister.io.state_in_1_0 := round.io.round_out_1_0
  stateRegister.io.state_in_2_0 := round.io.round_out_2_0
  stateRegister.io.state_in_3_0 := round.io.round_out_3_0
  stateRegister.io.state_in_4_0 := round.io.round_out_4_0
  stateRegister.io.state_in_0_1 := round.io.round_out_0_1
  stateRegister.io.state_in_1_1 := round.io.round_out_1_1
  stateRegister.io.state_in_2_1 := round.io.round_out_2_1
  stateRegister.io.state_in_3_1 := round.io.round_out_3_1
  stateRegister.io.state_in_4_1 := round.io.round_out_4_1
  stateRegister.io.state_in_0_2 := round.io.round_out_0_2
  stateRegister.io.state_in_1_2 := round.io.round_out_1_2
  stateRegister.io.state_in_2_2 := round.io.round_out_2_2
  stateRegister.io.state_in_3_2 := round.io.round_out_3_2
  stateRegister.io.state_in_4_2 := round.io.round_out_4_2
  stateRegister.io.state_in_0_3 := round.io.round_out_0_3
  stateRegister.io.state_in_1_3 := round.io.round_out_1_3
  stateRegister.io.state_in_2_3 := round.io.round_out_2_3
  stateRegister.io.state_in_3_3 := round.io.round_out_3_3
  stateRegister.io.state_in_4_3 := round.io.round_out_4_3
  stateRegister.io.state_in_0_4 := round.io.round_out_0_4
  stateRegister.io.state_in_1_4 := round.io.round_out_1_4
  stateRegister.io.state_in_2_4 := round.io.round_out_2_4
  stateRegister.io.state_in_3_4 := round.io.round_out_3_4
  stateRegister.io.state_in_4_4 := round.io.round_out_4_4

  io.round_out_0_0 := round.io.round_out_0_0
  io.round_out_1_0 := round.io.round_out_1_0
  io.round_out_2_0 := round.io.round_out_2_0
  io.round_out_3_0 := round.io.round_out_3_0
  io.round_out_4_0 := round.io.round_out_4_0
  io.round_out_0_1 := round.io.round_out_0_1
  io.round_out_1_1 := round.io.round_out_1_1
  io.round_out_2_1 := round.io.round_out_2_1
  io.round_out_3_1 := round.io.round_out_3_1
  io.round_out_4_1 := round.io.round_out_4_1
  io.round_out_0_2 := round.io.round_out_0_2
  io.round_out_1_2 := round.io.round_out_1_2
  io.round_out_2_2 := round.io.round_out_2_2
  io.round_out_3_2 := round.io.round_out_3_2
  io.round_out_4_2 := round.io.round_out_4_2
  io.round_out_0_3 := round.io.round_out_0_3
  io.round_out_1_3 := round.io.round_out_1_3
  io.round_out_2_3 := round.io.round_out_2_3
  io.round_out_3_3 := round.io.round_out_3_3
  io.round_out_4_3 := round.io.round_out_4_3
  io.round_out_0_4 := round.io.round_out_0_4
  io.round_out_1_4 := round.io.round_out_1_4
  io.round_out_2_4 := round.io.round_out_2_4
  io.round_out_3_4 := round.io.round_out_3_4
  io.round_out_4_4 := round.io.round_out_4_4

}
